/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellBanquetRouteImport } from './routes/_shell.banquet'
import { Route as ShellBillingRouteImport } from './routes/_shell.billing'
import { Route as ShellChannelManagerRouteImport } from './routes/_shell.channel-manager'
import { Route as ShellComplianceRouteImport } from './routes/_shell.compliance'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellFrontDeskRouteImport } from './routes/_shell.front-desk'
import { Route as ShellGuestsRouteImport } from './routes/_shell.guests'
import { Route as ShellHelpRouteImport } from './routes/_shell.help'
import { Route as ShellHousekeepingRouteImport } from './routes/_shell.housekeeping'
import { Route as ShellNightAuditRouteImport } from './routes/_shell.night-audit'
import { Route as ShellNotificationsRouteImport } from './routes/_shell.notifications'
import { Route as ShellPosRouteImport } from './routes/_shell.pos'
import { Route as ShellReportsRouteImport } from './routes/_shell.reports'
import { Route as ShellRevenueRouteImport } from './routes/_shell.revenue'
import { Route as ShellRoomsRouteImport } from './routes/_shell.rooms'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellStaffRouteImport } from './routes/_shell.staff'
import { Route as ShellProfitsRouteImport } from './routes/_shell.profits'
import { Route as ShellExpensesRouteImport } from './routes/_shell.expenses'
import { Route as ShellDiscountsRouteImport } from './routes/_shell.discounts'
import { Route as ShellPendingPaymentsRouteImport } from './routes/_shell.pending-payments'
import { Route as ShellPaymentHistoryRouteImport } from './routes/_shell.payment-history'
import { Route as ShellPaymentsRouteImport } from './routes/_shell.payments'
import { Route as ShellPartyHallRouteImport } from './routes/_shell.party-hall'
import { Route as ShellVisitorsRouteImport } from './routes/_shell.visitors'
import { Route as ShellComplaintsRouteImport } from './routes/_shell.complaints'
import { Route as ShellReservationsIndexRouteImport } from './routes/_shell.reservations.index'
import { Route as ShellReservationsNewRouteImport } from './routes/_shell.reservations.new'
import { Route as ShellSystemWorkflowRouteImport } from './routes/_shell.system-workflow'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellBanquetRoute = ShellBanquetRouteImport.update({
  id: '/banquet',
  path: '/banquet',
  getParentRoute: () => ShellRoute,
} as any)
const ShellBillingRoute = ShellBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => ShellRoute,
} as any)
const ShellChannelManagerRoute = ShellChannelManagerRouteImport.update({
  id: '/channel-manager',
  path: '/channel-manager',
  getParentRoute: () => ShellRoute,
} as any)
const ShellComplianceRoute = ShellComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFrontDeskRoute = ShellFrontDeskRouteImport.update({
  id: '/front-desk',
  path: '/front-desk',
  getParentRoute: () => ShellRoute,
} as any)
const ShellGuestsRoute = ShellGuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => ShellRoute,
} as any)
const ShellHelpRoute = ShellHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => ShellRoute,
} as any)
const ShellHousekeepingRoute = ShellHousekeepingRouteImport.update({
  id: '/housekeeping',
  path: '/housekeeping',
  getParentRoute: () => ShellRoute,
} as any)
const ShellNightAuditRoute = ShellNightAuditRouteImport.update({
  id: '/night-audit',
  path: '/night-audit',
  getParentRoute: () => ShellRoute,
} as any)
const ShellNotificationsRoute = ShellNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPosRoute = ShellPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReportsRoute = ShellReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRevenueRoute = ShellRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRoomsRoute = ShellRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellStaffRoute = ShellStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProfitsRoute = ShellProfitsRouteImport.update({
  id: '/profits',
  path: '/profits',
  getParentRoute: () => ShellRoute,
} as any)
const ShellExpensesRoute = ShellExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDiscountsRoute = ShellDiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPendingPaymentsRoute = ShellPendingPaymentsRouteImport.update({
  id: '/pending-payments',
  path: '/pending-payments',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPaymentHistoryRoute = ShellPaymentHistoryRouteImport.update({
  id: '/payment-history',
  path: '/payment-history',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPaymentsRoute = ShellPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPartyHallRoute = ShellPartyHallRouteImport.update({
  id: '/party-hall',
  path: '/party-hall',
  getParentRoute: () => ShellRoute,
} as any)
const ShellVisitorsRoute = ShellVisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => ShellRoute,
} as any)
const ShellComplaintsRoute = ShellComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReservationsIndexRoute = ShellReservationsIndexRouteImport.update({
  id: '/reservations/',
  path: '/reservations/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReservationsNewRoute = ShellReservationsNewRouteImport.update({
  id: '/reservations/new',
  path: '/reservations/new',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/banquet': typeof ShellBanquetRoute
  '/billing': typeof ShellBillingRoute
  '/channel-manager': typeof ShellChannelManagerRoute
  '/compliance': typeof ShellComplianceRoute
  '/dashboard': typeof ShellDashboardRoute
  '/front-desk': typeof ShellFrontDeskRoute
  '/guests': typeof ShellGuestsRoute
  '/help': typeof ShellHelpRoute
  '/housekeeping': typeof ShellHousekeepingRoute
  '/night-audit': typeof ShellNightAuditRoute
  '/notifications': typeof ShellNotificationsRoute
  '/pos': typeof ShellPosRoute
  '/reports': typeof ShellReportsRoute
  '/revenue': typeof ShellRevenueRoute
  '/rooms': typeof ShellRoomsRoute
  '/settings': typeof ShellSettingsRoute
  '/staff': typeof ShellStaffRoute
  '/reservations/new': typeof ShellReservationsNewRoute
  '/reservations/': typeof ShellReservationsIndexRoute
  '/system-workflow': typeof ShellSystemWorkflowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/banquet': typeof ShellBanquetRoute
  '/billing': typeof ShellBillingRoute
  '/channel-manager': typeof ShellChannelManagerRoute
  '/compliance': typeof ShellComplianceRoute
  '/dashboard': typeof ShellDashboardRoute
  '/front-desk': typeof ShellFrontDeskRoute
  '/guests': typeof ShellGuestsRoute
  '/help': typeof ShellHelpRoute
  '/housekeeping': typeof ShellHousekeepingRoute
  '/night-audit': typeof ShellNightAuditRoute
  '/notifications': typeof ShellNotificationsRoute
  '/pos': typeof ShellPosRoute
  '/reports': typeof ShellReportsRoute
  '/revenue': typeof ShellRevenueRoute
  '/rooms': typeof ShellRoomsRoute
  '/settings': typeof ShellSettingsRoute
  '/staff': typeof ShellStaffRoute
  '/reservations/new': typeof ShellReservationsNewRoute
  '/reservations': typeof ShellReservationsIndexRoute
  '/system-workflow': typeof ShellSystemWorkflowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/banquet': typeof ShellBanquetRoute
  '/_shell/billing': typeof ShellBillingRoute
  '/_shell/channel-manager': typeof ShellChannelManagerRoute
  '/_shell/compliance': typeof ShellComplianceRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/front-desk': typeof ShellFrontDeskRoute
  '/_shell/guests': typeof ShellGuestsRoute
  '/_shell/help': typeof ShellHelpRoute
  '/_shell/housekeeping': typeof ShellHousekeepingRoute
  '/_shell/night-audit': typeof ShellNightAuditRoute
  '/_shell/notifications': typeof ShellNotificationsRoute
  '/_shell/pos': typeof ShellPosRoute
  '/_shell/reports': typeof ShellReportsRoute
  '/_shell/revenue': typeof ShellRevenueRoute
  '/_shell/rooms': typeof ShellRoomsRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/staff': typeof ShellStaffRoute
  '/_shell/reservations/new': typeof ShellReservationsNewRoute
  '/_shell/reservations/': typeof ShellReservationsIndexRoute
  '/_shell/system-workflow': typeof ShellSystemWorkflowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/banquet'
    | '/billing'
    | '/channel-manager'
    | '/compliance'
    | '/dashboard'
    | '/front-desk'
    | '/guests'
    | '/help'
    | '/housekeeping'
    | '/night-audit'
    | '/notifications'
    | '/pos'
    | '/reports'
    | '/revenue'
    | '/rooms'
    | '/settings'
    | '/staff'
    | '/reservations/new'
    | '/reservations/'
    | '/system-workflow'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/banquet'
    | '/billing'
    | '/channel-manager'
    | '/compliance'
    | '/dashboard'
    | '/front-desk'
    | '/guests'
    | '/help'
    | '/housekeeping'
    | '/night-audit'
    | '/notifications'
    | '/pos'
    | '/reports'
    | '/revenue'
    | '/rooms'
    | '/settings'
    | '/staff'
    | '/reservations/new'
    | '/reservations'
    | '/system-workflow'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/_shell/banquet'
    | '/_shell/billing'
    | '/_shell/channel-manager'
    | '/_shell/compliance'
    | '/_shell/dashboard'
    | '/_shell/front-desk'
    | '/_shell/guests'
    | '/_shell/help'
    | '/_shell/housekeeping'
    | '/_shell/night-audit'
    | '/_shell/notifications'
    | '/_shell/pos'
    | '/_shell/reports'
    | '/_shell/revenue'
    | '/_shell/rooms'
    | '/_shell/settings'
    | '/_shell/staff'
    | '/_shell/reservations/new'
    | '/_shell/reservations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/banquet': {
      id: '/_shell/banquet'
      path: '/banquet'
      fullPath: '/banquet'
      preLoaderRoute: typeof ShellBanquetRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/billing': {
      id: '/_shell/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof ShellBillingRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/channel-manager': {
      id: '/_shell/channel-manager'
      path: '/channel-manager'
      fullPath: '/channel-manager'
      preLoaderRoute: typeof ShellChannelManagerRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/compliance': {
      id: '/_shell/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ShellComplianceRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/front-desk': {
      id: '/_shell/front-desk'
      path: '/front-desk'
      fullPath: '/front-desk'
      preLoaderRoute: typeof ShellFrontDeskRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/guests': {
      id: '/_shell/guests'
      path: '/guests'
      fullPath: '/guests'
      preLoaderRoute: typeof ShellGuestsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/help': {
      id: '/_shell/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof ShellHelpRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/housekeeping': {
      id: '/_shell/housekeeping'
      path: '/housekeeping'
      fullPath: '/housekeeping'
      preLoaderRoute: typeof ShellHousekeepingRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/night-audit': {
      id: '/_shell/night-audit'
      path: '/night-audit'
      fullPath: '/night-audit'
      preLoaderRoute: typeof ShellNightAuditRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/notifications': {
      id: '/_shell/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof ShellNotificationsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/pos': {
      id: '/_shell/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof ShellPosRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/reports': {
      id: '/_shell/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ShellReportsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/revenue': {
      id: '/_shell/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof ShellRevenueRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/rooms': {
      id: '/_shell/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof ShellRoomsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/staff': {
      id: '/_shell/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof ShellStaffRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/reservations/': {
      id: '/_shell/reservations/'
      path: '/reservations'
      fullPath: '/reservations/'
      preLoaderRoute: typeof ShellReservationsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/reservations/new': {
      id: '/_shell/reservations/new'
      path: '/reservations/new'
      fullPath: '/reservations/new'
      preLoaderRoute: typeof ShellReservationsNewRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/system-workflow': {
      id: '/_shell/system-workflow'
      path: '/system-workflow'
      fullPath: '/system-workflow'
      preLoaderRoute: typeof ShellSystemWorkflowRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellBanquetRoute: typeof ShellBanquetRoute
  ShellBillingRoute: typeof ShellBillingRoute
  ShellChannelManagerRoute: typeof ShellChannelManagerRoute
  ShellComplianceRoute: typeof ShellComplianceRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellFrontDeskRoute: typeof ShellFrontDeskRoute
  ShellGuestsRoute: typeof ShellGuestsRoute
  ShellHelpRoute: typeof ShellHelpRoute
  ShellHousekeepingRoute: typeof ShellHousekeepingRoute
  ShellNightAuditRoute: typeof ShellNightAuditRoute
  ShellNotificationsRoute: typeof ShellNotificationsRoute
  ShellPosRoute: typeof ShellPosRoute
  ShellReportsRoute: typeof ShellReportsRoute
  ShellRevenueRoute: typeof ShellRevenueRoute
  ShellRoomsRoute: typeof ShellRoomsRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellStaffRoute: typeof ShellStaffRoute
  ShellReservationsNewRoute: typeof ShellReservationsNewRoute
  ShellReservationsIndexRoute: typeof ShellReservationsIndexRoute
  ShellSystemWorkflowRoute: typeof ShellSystemWorkflowRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellBanquetRoute: ShellBanquetRoute,
  ShellBillingRoute: ShellBillingRoute,
  ShellChannelManagerRoute: ShellChannelManagerRoute,
  ShellComplianceRoute: ShellComplianceRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellFrontDeskRoute: ShellFrontDeskRoute,
  ShellGuestsRoute: ShellGuestsRoute,
  ShellHelpRoute: ShellHelpRoute,
  ShellHousekeepingRoute: ShellHousekeepingRoute,
  ShellNightAuditRoute: ShellNightAuditRoute,
  ShellNotificationsRoute: ShellNotificationsRoute,
  ShellPosRoute: ShellPosRoute,
  ShellReportsRoute: ShellReportsRoute,
  ShellRevenueRoute: ShellRevenueRoute,
  ShellRoomsRoute: ShellRoomsRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellStaffRoute: ShellStaffRoute,
  ShellProfitsRoute: ShellProfitsRoute,
  ShellExpensesRoute: ShellExpensesRoute,
  ShellDiscountsRoute: ShellDiscountsRoute,
  ShellPendingPaymentsRoute: ShellPendingPaymentsRoute,
  ShellPaymentHistoryRoute: ShellPaymentHistoryRoute,
  ShellPaymentsRoute: ShellPaymentsRoute,
  ShellPartyHallRoute: ShellPartyHallRoute,
  ShellVisitorsRoute: ShellVisitorsRoute,
  ShellComplaintsRoute: ShellComplaintsRoute,
  ShellReservationsNewRoute: ShellReservationsNewRoute,
  ShellReservationsIndexRoute: ShellReservationsIndexRoute,
  ShellSystemWorkflowRoute: ShellSystemWorkflowRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
